version: '3.8'

services:

    fakeSmtp:
        container_name: fakeSmtpServer
        image: rnwood/smtp4dev:v3
        ports:
            - '5000:80' # WebInterface
            - '5001:25' # SMTP server
            - '5002:143' # IMAP server
        volumes:
            - ./smtp4dev-data:/smtp4dev
        environment:
            - ServerOptions__BasePath=/
            - ServerOptions__HostName=smtp4dev
            - RelayOptions__SmtpPort=5003
            - RelayOptions__ImapPort=5004
            - RelayOptions__Login=admin
            - RelayOptions__Password=admin

    postgres:
        container_name: postgresDB
        image: postgres:15
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"


    pgAdmin:
        container_name: postgresAdminer
        image: dpage/pgadmin4:6.21
        ports:
            - "8080:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.de
            - PGADMIN_DEFAULT_PASSWORD=admin

    node:
        container_name: node_server
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        stdin_open: true
        volumes:
            - ./backend:/usr/src/app/